; CRDW INI
; types are prefixed with b, i, s
; b(boolean) true, false
; i(integer) 64bit signed number
; s(string) text

[General]
Logging=b:true
LogFlush=i:2
ShowPopUp=b:true
Mode=s:LOAD

[Optimization]
IOBuffer=i:262144
Experimental=b:false