; CRDW INI
; types are prefixed with b, i, s
; b(boolean) true, false
; i(integer) 64bit signed number
; s(string) text

[General]
ShowPopUp=b:true
Mode=s:LOAD
Logging=b:true
Debug=b:false
LogFlush=i:2
CacheDirectory=s:Data/SKSE/Plugins/

[Optimization]
IOBuffer=i:262144
Experimental=b:false